---
- name:  Update pentest:children servers
  hosts: pentest-todo
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update pentest:children server
  hosts: pentest-tooling
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: create directory, file and set timezone on all servers
  hosts: webservers, nfs, db 
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: create a directory
      file:
        path: /home/sample
        state: directory
    - name: create a directory
      file:
        path: /home/sample/ansible.txt
        state: touch
    - name: set timezone
      timezone:
          name: Africa/Lagos   

          



